# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import fastreport_cloud_sdk
from fastreport_cloud_sdk.models.server_configuration_vm import ServerConfigurationVM  # noqa: E501
from fastreport_cloud_sdk.rest import ApiException

class TestServerConfigurationVM(unittest.TestCase):
    """ServerConfigurationVM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ServerConfigurationVM
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = fastreport_cloud_sdk.models.server_configuration_vm.ServerConfigurationVM()  # noqa: E501
        if include_optional :
            return ServerConfigurationVM(
                title = '', 
                logo_link = '', 
                copyright = '', 
                corporate_server_mode = True, 
                last_sla_version = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                is_disabled = True, 
                frontend = fastreport_cloud_sdk.models.frontend_app.FrontendApp(
                    mixins = fastreport_cloud_sdk.models.app_mixins.AppMixins(
                        head = '', 
                        body = '', ), ), 
                invariant_locale = '', 
                auth = fastreport_cloud_sdk.models.auth_config_vm.AuthConfigVM(
                    use_local = True, 
                    use_open_id = True, 
                    authority = '', ), 
                designer_for_anons = True, 
                sla_link = '', 
                first_steps_video_link = '', 
                about_link = '', 
                home_page_link = '', 
                auth_server_name = '', 
                update_workspace_link = ''
            )
        else :
            return ServerConfigurationVM(
        )

    def testServerConfigurationVM(self):
        """Test ServerConfigurationVM"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
