# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import fastreport_cloud_sdk
from fastreport_cloud_sdk.models.group_create_group_get_group_update_group_delete_group_execute_group_administrate_permission import GroupCreateGroupGetGroupUpdateGroupDeleteGroupExecuteGroupAdministratePermission  # noqa: E501
from fastreport_cloud_sdk.rest import ApiException

class TestGroupCreateGroupGetGroupUpdateGroupDeleteGroupExecuteGroupAdministratePermission(unittest.TestCase):
    """GroupCreateGroupGetGroupUpdateGroupDeleteGroupExecuteGroupAdministratePermission unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GroupCreateGroupGetGroupUpdateGroupDeleteGroupExecuteGroupAdministratePermission
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = fastreport_cloud_sdk.models.group_create_group_get_group_update_group_delete_group_execute_group_administrate_permission.GroupCreateGroupGetGroupUpdateGroupDeleteGroupExecuteGroupAdministratePermission()  # noqa: E501
        if include_optional :
            return GroupCreateGroupGetGroupUpdateGroupDeleteGroupExecuteGroupAdministratePermission(
                create = 0, 
                delete = 0, 
                execute = 0, 
                get = 0, 
                update = 0, 
                administrate = 0
            )
        else :
            return GroupCreateGroupGetGroupUpdateGroupDeleteGroupExecuteGroupAdministratePermission(
        )

    def testGroupCreateGroupGetGroupUpdateGroupDeleteGroupExecuteGroupAdministratePermission(self):
        """Test GroupCreateGroupGetGroupUpdateGroupDeleteGroupExecuteGroupAdministratePermission"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
