# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import fastreport_cloud_sdk
from fastreport_cloud_sdk.api.admin_groups_api import AdminGroupsApi  # noqa: E501
from fastreport_cloud_sdk.rest import ApiException


class TestAdminGroupsApi(unittest.TestCase):
    """AdminGroupsApi unit test stubs"""

    def setUp(self):
        self.api = fastreport_cloud_sdk.api.admin_groups_api.AdminGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_groups_create_group(self):
        """Test case for admin_groups_create_group

        Create a new group, returns a new model  # noqa: E501
        """
        pass

    def test_admin_groups_delete_group(self):
        """Test case for admin_groups_delete_group

        Delete a group by id  # noqa: E501
        """
        pass

    def test_admin_groups_get_group(self):
        """Test case for admin_groups_get_group

        Returns a group by id  # noqa: E501
        """
        pass

    def test_admin_groups_get_groups(self):
        """Test case for admin_groups_get_groups

        Returns a list of groups  # noqa: E501
        """
        pass

    def test_admin_groups_get_permissions(self):
        """Test case for admin_groups_get_permissions

        Gets group permissions by identifier  # noqa: E501
        """
        pass

    def test_admin_groups_update_group(self):
        """Test case for admin_groups_update_group

        Update a group by id  # noqa: E501
        """
        pass

    def test_admin_groups_update_permissions(self):
        """Test case for admin_groups_update_permissions

        Update permissions in user group by identifier  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
