# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import fastreport_cloud_sdk
from fastreport_cloud_sdk.api.configuration_api import ConfigurationApi  # noqa: E501
from fastreport_cloud_sdk.rest import ApiException


class TestConfigurationApi(unittest.TestCase):
    """ConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = fastreport_cloud_sdk.api.configuration_api.ConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_configuration_get(self):
        """Test case for configuration_get

        returns information about server configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
