# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import fastreport_cloud_sdk
from fastreport_cloud_sdk.models.prepare_template_vm import PrepareTemplateVM  # noqa: E501
from fastreport_cloud_sdk.rest import ApiException

class TestPrepareTemplateVM(unittest.TestCase):
    """PrepareTemplateVM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PrepareTemplateVM
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = fastreport_cloud_sdk.models.prepare_template_vm.PrepareTemplateVM()  # noqa: E501
        if include_optional :
            return PrepareTemplateVM(
                name = '0', 
                locale = 'EiOT-wW', 
                parent_folder_id = '2ECB020842930cc01FFCCfeE', 
                pages_count = 0, 
                report_parameters = {
                    'key' : ''
                    }
            )
        else :
            return PrepareTemplateVM(
        )

    def testPrepareTemplateVM(self):
        """Test PrepareTemplateVM"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
