# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import fastreport_cloud_sdk
from fastreport_cloud_sdk.models.data_sources_vm import DataSourcesVM  # noqa: E501
from fastreport_cloud_sdk.rest import ApiException

class TestDataSourcesVM(unittest.TestCase):
    """DataSourcesVM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DataSourcesVM
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = fastreport_cloud_sdk.models.data_sources_vm.DataSourcesVM()  # noqa: E501
        if include_optional :
            return DataSourcesVM(
                data_sources = [
                    fastreport_cloud_sdk.models.data_source_vm.DataSourceVM(
                        id = '', 
                        name = '', 
                        connection_type = 'JSON', 
                        connection_string = '', 
                        data_structure = '', 
                        subscription_id = '', 
                        edited_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        editor_user_id = '', 
                        created_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        creator_user_id = '', 
                        is_connected = True, )
                    ], 
                count = 56, 
                skip = 56, 
                take = 56
            )
        else :
            return DataSourcesVM(
        )

    def testDataSourcesVM(self):
        """Test DataSourcesVM"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
