# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import fastreport_cloud_sdk
from fastreport_cloud_sdk.api.download_api import DownloadApi  # noqa: E501
from fastreport_cloud_sdk.rest import ApiException


class TestDownloadApi(unittest.TestCase):
    """DownloadApi unit test stubs"""

    def setUp(self):
        self.api = fastreport_cloud_sdk.api.download_api.DownloadApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_get_export(self):
        """Test case for download_get_export

        Returns a export file with specified id  # noqa: E501
        """
        pass

    def test_download_get_export_thumbnail(self):
        """Test case for download_get_export_thumbnail

        Returns export's thumbnail  # noqa: E501
        """
        pass

    def test_download_get_exports(self):
        """Test case for download_get_exports

        Returns a zip archive with selected ids  # noqa: E501
        """
        pass

    def test_download_get_report(self):
        """Test case for download_get_report

        Returns a prepared file with specified id  # noqa: E501
        """
        pass

    def test_download_get_report_thumbnail(self):
        """Test case for download_get_report_thumbnail

        Returns report's thumbnail  # noqa: E501
        """
        pass

    def test_download_get_reports(self):
        """Test case for download_get_reports

        Returns a zip archive with selected files  # noqa: E501
        """
        pass

    def test_download_get_template(self):
        """Test case for download_get_template

        Returns a Template file with specified id  # noqa: E501
        """
        pass

    def test_download_get_template_thumbnail(self):
        """Test case for download_get_template_thumbnail

        Returns template's thumbnail  # noqa: E501
        """
        pass

    def test_download_get_templates(self):
        """Test case for download_get_templates

        Returns a zip archive with selected files  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
