# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import fastreport_cloud_sdk
from fastreport_cloud_sdk.api.contact_groups_api import ContactGroupsApi  # noqa: E501
from fastreport_cloud_sdk.rest import ApiException


class TestContactGroupsApi(unittest.TestCase):
    """ContactGroupsApi unit test stubs"""

    def setUp(self):
        self.api = fastreport_cloud_sdk.api.contact_groups_api.ContactGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contact_groups_create(self):
        """Test case for contact_groups_create

        Creates contact group  # noqa: E501
        """
        pass

    def test_contact_groups_delete(self):
        """Test case for contact_groups_delete

        Removes contact by id  # noqa: E501
        """
        pass

    def test_contact_groups_get(self):
        """Test case for contact_groups_get

        Returns contact group by id  # noqa: E501
        """
        pass

    def test_contact_groups_get_list(self):
        """Test case for contact_groups_get_list

        Returns contact groups by subscriptionId  # noqa: E501
        """
        pass

    def test_contact_groups_update(self):
        """Test case for contact_groups_update

        Updates contact group by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
