# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import fastreport_cloud_sdk
from fastreport_cloud_sdk.api.admin_health_check_api import AdminHealthCheckApi  # noqa: E501
from fastreport_cloud_sdk.rest import ApiException


class TestAdminHealthCheckApi(unittest.TestCase):
    """AdminHealthCheckApi unit test stubs"""

    def setUp(self):
        self.api = fastreport_cloud_sdk.api.admin_health_check_api.AdminHealthCheckApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_health_check_admin_get(self):
        """Test case for admin_health_check_admin_get

        healthcheck  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
