# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import fastreport_cloud_sdk
from fastreport_cloud_sdk.models.subscription_invites_vm import SubscriptionInvitesVM  # noqa: E501
from fastreport_cloud_sdk.rest import ApiException

class TestSubscriptionInvitesVM(unittest.TestCase):
    """SubscriptionInvitesVM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SubscriptionInvitesVM
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = fastreport_cloud_sdk.models.subscription_invites_vm.SubscriptionInvitesVM()  # noqa: E501
        if include_optional :
            return SubscriptionInvitesVM(
                invites = [
                    fastreport_cloud_sdk.models.subscription_invite_vm.SubscriptionInviteVM(
                        usages = 56, 
                        durable = True, 
                        access_token = '', 
                        expired_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        added_users = [
                            fastreport_cloud_sdk.models.invited_user.InvitedUser(
                                user_id = '', 
                                invited_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], 
                        creator_user_id = '', )
                    ], 
                count = 56
            )
        else :
            return SubscriptionInvitesVM(
        )

    def testSubscriptionInvitesVM(self):
        """Test SubscriptionInvitesVM"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
