# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import fastreport_cloud_sdk
from fastreport_cloud_sdk.api.admin_subscription_invites_api import AdminSubscriptionInvitesApi  # noqa: E501
from fastreport_cloud_sdk.rest import ApiException


class TestAdminSubscriptionInvitesApi(unittest.TestCase):
    """AdminSubscriptionInvitesApi unit test stubs"""

    def setUp(self):
        self.api = fastreport_cloud_sdk.api.admin_subscription_invites_api.AdminSubscriptionInvitesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_subscription_invites_create_invite(self):
        """Test case for admin_subscription_invites_create_invite

        Create invite to subscription  # noqa: E501
        """
        pass

    def test_admin_subscription_invites_delete_invite(self):
        """Test case for admin_subscription_invites_delete_invite

        Rename subscription  # noqa: E501
        """
        pass

    def test_admin_subscription_invites_get_invites(self):
        """Test case for admin_subscription_invites_get_invites

        Get list of invites in a subscription,  the added users will be displayed in the list of users of the subscription,  and these users will also have an active subscription.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
