# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from fastreport_cloud_sdk.configuration import Configuration


class AuditFilePropertyChangedVM(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'property_name': 'str',
        'old_value': 'object',
        'new_value': 'object',
        'admin_action': 'bool',
        'user_id': 'str',
        'entity_id': 'str',
        'subscription_id': 'str',
        'type': 'AuditType',
        'id': 'str',
        'created_time': 'datetime',
        'creator_user_id': 'str',
        'name': 'str'
    }

    attribute_map = {
        'property_name': 'propertyName',
        'old_value': 'oldValue',
        'new_value': 'newValue',
        'admin_action': 'adminAction',
        'user_id': 'userId',
        'entity_id': 'entityId',
        'subscription_id': 'subscriptionId',
        'type': 'type',
        'id': 'id',
        'created_time': 'createdTime',
        'creator_user_id': 'creatorUserId',
        'name': 'name'
    }

    def __init__(self, property_name=None, old_value=None, new_value=None, admin_action=None, user_id=None, entity_id=None, subscription_id=None, type=None, id=None, created_time=None, creator_user_id=None, name=None, local_vars_configuration=None):  # noqa: E501
        """AuditFilePropertyChangedVM - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._property_name = None
        self._old_value = None
        self._new_value = None
        self._admin_action = None
        self._user_id = None
        self._entity_id = None
        self._subscription_id = None
        self._type = None
        self._id = None
        self._created_time = None
        self._creator_user_id = None
        self._name = None
        self.discriminator = None

        self.property_name = property_name
        self.old_value = old_value
        self.new_value = new_value
        if admin_action is not None:
            self.admin_action = admin_action
        self.user_id = user_id
        self.entity_id = entity_id
        self.subscription_id = subscription_id
        if type is not None:
            self.type = type
        self.id = id
        if created_time is not None:
            self.created_time = created_time
        self.creator_user_id = creator_user_id
        self.name = name

    @property
    def property_name(self):
        """Gets the property_name of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The property_name of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: str
        """
        return self._property_name

    @property_name.setter
    def property_name(self, property_name):
        """Sets the property_name of this AuditFilePropertyChangedVM.


        :param property_name: The property_name of this AuditFilePropertyChangedVM.  # noqa: E501
        :type property_name: str
        """

        self._property_name = property_name

    @property
    def old_value(self):
        """Gets the old_value of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The old_value of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: object
        """
        return self._old_value

    @old_value.setter
    def old_value(self, old_value):
        """Sets the old_value of this AuditFilePropertyChangedVM.


        :param old_value: The old_value of this AuditFilePropertyChangedVM.  # noqa: E501
        :type old_value: object
        """

        self._old_value = old_value

    @property
    def new_value(self):
        """Gets the new_value of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The new_value of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: object
        """
        return self._new_value

    @new_value.setter
    def new_value(self, new_value):
        """Sets the new_value of this AuditFilePropertyChangedVM.


        :param new_value: The new_value of this AuditFilePropertyChangedVM.  # noqa: E501
        :type new_value: object
        """

        self._new_value = new_value

    @property
    def admin_action(self):
        """Gets the admin_action of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The admin_action of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: bool
        """
        return self._admin_action

    @admin_action.setter
    def admin_action(self, admin_action):
        """Sets the admin_action of this AuditFilePropertyChangedVM.


        :param admin_action: The admin_action of this AuditFilePropertyChangedVM.  # noqa: E501
        :type admin_action: bool
        """

        self._admin_action = admin_action

    @property
    def user_id(self):
        """Gets the user_id of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The user_id of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this AuditFilePropertyChangedVM.


        :param user_id: The user_id of this AuditFilePropertyChangedVM.  # noqa: E501
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def entity_id(self):
        """Gets the entity_id of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The entity_id of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: str
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """Sets the entity_id of this AuditFilePropertyChangedVM.


        :param entity_id: The entity_id of this AuditFilePropertyChangedVM.  # noqa: E501
        :type entity_id: str
        """

        self._entity_id = entity_id

    @property
    def subscription_id(self):
        """Gets the subscription_id of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The subscription_id of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: str
        """
        return self._subscription_id

    @subscription_id.setter
    def subscription_id(self, subscription_id):
        """Sets the subscription_id of this AuditFilePropertyChangedVM.


        :param subscription_id: The subscription_id of this AuditFilePropertyChangedVM.  # noqa: E501
        :type subscription_id: str
        """

        self._subscription_id = subscription_id

    @property
    def type(self):
        """Gets the type of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The type of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: AuditType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AuditFilePropertyChangedVM.


        :param type: The type of this AuditFilePropertyChangedVM.  # noqa: E501
        :type type: AuditType
        """

        self._type = type

    @property
    def id(self):
        """Gets the id of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The id of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AuditFilePropertyChangedVM.


        :param id: The id of this AuditFilePropertyChangedVM.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def created_time(self):
        """Gets the created_time of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The created_time of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: datetime
        """
        return self._created_time

    @created_time.setter
    def created_time(self, created_time):
        """Sets the created_time of this AuditFilePropertyChangedVM.


        :param created_time: The created_time of this AuditFilePropertyChangedVM.  # noqa: E501
        :type created_time: datetime
        """

        self._created_time = created_time

    @property
    def creator_user_id(self):
        """Gets the creator_user_id of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The creator_user_id of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: str
        """
        return self._creator_user_id

    @creator_user_id.setter
    def creator_user_id(self, creator_user_id):
        """Sets the creator_user_id of this AuditFilePropertyChangedVM.


        :param creator_user_id: The creator_user_id of this AuditFilePropertyChangedVM.  # noqa: E501
        :type creator_user_id: str
        """

        self._creator_user_id = creator_user_id

    @property
    def name(self):
        """Gets the name of this AuditFilePropertyChangedVM.  # noqa: E501


        :return: The name of this AuditFilePropertyChangedVM.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AuditFilePropertyChangedVM.


        :param name: The name of this AuditFilePropertyChangedVM.  # noqa: E501
        :type name: str
        """

        self._name = name

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuditFilePropertyChangedVM):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AuditFilePropertyChangedVM):
            return True

        return self.to_dict() != other.to_dict()
