# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from fastreport_cloud_sdk.configuration import Configuration


class CreateSubscriptionInviteVM(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'usages': 'int',
        'durable': 'bool',
        'expired_date': 'datetime'
    }

    attribute_map = {
        'usages': 'usages',
        'durable': 'durable',
        'expired_date': 'expiredDate'
    }

    def __init__(self, usages=None, durable=None, expired_date=None, local_vars_configuration=None):  # noqa: E501
        """CreateSubscriptionInviteVM - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._usages = None
        self._durable = None
        self._expired_date = None
        self.discriminator = None

        if usages is not None:
            self.usages = usages
        if durable is not None:
            self.durable = durable
        if expired_date is not None:
            self.expired_date = expired_date

    @property
    def usages(self):
        """Gets the usages of this CreateSubscriptionInviteVM.  # noqa: E501


        :return: The usages of this CreateSubscriptionInviteVM.  # noqa: E501
        :rtype: int
        """
        return self._usages

    @usages.setter
    def usages(self, usages):
        """Sets the usages of this CreateSubscriptionInviteVM.


        :param usages: The usages of this CreateSubscriptionInviteVM.  # noqa: E501
        :type usages: int
        """
        if (self.local_vars_configuration.client_side_validation and
                usages is not None and usages > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `usages`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                usages is not None and usages < 0):  # noqa: E501
            raise ValueError("Invalid value for `usages`, must be a value greater than or equal to `0`")  # noqa: E501

        self._usages = usages

    @property
    def durable(self):
        """Gets the durable of this CreateSubscriptionInviteVM.  # noqa: E501


        :return: The durable of this CreateSubscriptionInviteVM.  # noqa: E501
        :rtype: bool
        """
        return self._durable

    @durable.setter
    def durable(self, durable):
        """Sets the durable of this CreateSubscriptionInviteVM.


        :param durable: The durable of this CreateSubscriptionInviteVM.  # noqa: E501
        :type durable: bool
        """

        self._durable = durable

    @property
    def expired_date(self):
        """Gets the expired_date of this CreateSubscriptionInviteVM.  # noqa: E501


        :return: The expired_date of this CreateSubscriptionInviteVM.  # noqa: E501
        :rtype: datetime
        """
        return self._expired_date

    @expired_date.setter
    def expired_date(self, expired_date):
        """Sets the expired_date of this CreateSubscriptionInviteVM.


        :param expired_date: The expired_date of this CreateSubscriptionInviteVM.  # noqa: E501
        :type expired_date: datetime
        """

        self._expired_date = expired_date

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateSubscriptionInviteVM):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateSubscriptionInviteVM):
            return True

        return self.to_dict() != other.to_dict()
