# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from fastreport_cloud_sdk.configuration import Configuration


class RunExportReportTaskVM(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'export_parameters': 'dict(str, str)',
        'format': 'ExportFormat',
        'pages_count': 'int',
        'subscription_id': 'str',
        'type': 'TaskType'
    }

    attribute_map = {
        'export_parameters': 'exportParameters',
        'format': 'format',
        'pages_count': 'pagesCount',
        'subscription_id': 'subscriptionId',
        'type': 'type'
    }

    def __init__(self, export_parameters=None, format=None, pages_count=None, subscription_id=None, type=None, local_vars_configuration=None):  # noqa: E501
        """RunExportReportTaskVM - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._export_parameters = None
        self._format = None
        self._pages_count = None
        self._subscription_id = None
        self._type = None
        self.discriminator = None

        self.export_parameters = export_parameters
        if format is not None:
            self.format = format
        self.pages_count = pages_count
        self.subscription_id = subscription_id
        if type is not None:
            self.type = type

    @property
    def export_parameters(self):
        """Gets the export_parameters of this RunExportReportTaskVM.  # noqa: E501


        :return: The export_parameters of this RunExportReportTaskVM.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._export_parameters

    @export_parameters.setter
    def export_parameters(self, export_parameters):
        """Sets the export_parameters of this RunExportReportTaskVM.


        :param export_parameters: The export_parameters of this RunExportReportTaskVM.  # noqa: E501
        :type export_parameters: dict(str, str)
        """

        self._export_parameters = export_parameters

    @property
    def format(self):
        """Gets the format of this RunExportReportTaskVM.  # noqa: E501


        :return: The format of this RunExportReportTaskVM.  # noqa: E501
        :rtype: ExportFormat
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this RunExportReportTaskVM.


        :param format: The format of this RunExportReportTaskVM.  # noqa: E501
        :type format: ExportFormat
        """

        self._format = format

    @property
    def pages_count(self):
        """Gets the pages_count of this RunExportReportTaskVM.  # noqa: E501


        :return: The pages_count of this RunExportReportTaskVM.  # noqa: E501
        :rtype: int
        """
        return self._pages_count

    @pages_count.setter
    def pages_count(self, pages_count):
        """Sets the pages_count of this RunExportReportTaskVM.


        :param pages_count: The pages_count of this RunExportReportTaskVM.  # noqa: E501
        :type pages_count: int
        """
        if (self.local_vars_configuration.client_side_validation and
                pages_count is not None and pages_count > 2147483647):  # noqa: E501
            raise ValueError("Invalid value for `pages_count`, must be a value less than or equal to `2147483647`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                pages_count is not None and pages_count < 0):  # noqa: E501
            raise ValueError("Invalid value for `pages_count`, must be a value greater than or equal to `0`")  # noqa: E501

        self._pages_count = pages_count

    @property
    def subscription_id(self):
        """Gets the subscription_id of this RunExportReportTaskVM.  # noqa: E501


        :return: The subscription_id of this RunExportReportTaskVM.  # noqa: E501
        :rtype: str
        """
        return self._subscription_id

    @subscription_id.setter
    def subscription_id(self, subscription_id):
        """Sets the subscription_id of this RunExportReportTaskVM.


        :param subscription_id: The subscription_id of this RunExportReportTaskVM.  # noqa: E501
        :type subscription_id: str
        """
        if (self.local_vars_configuration.client_side_validation and
                subscription_id is not None and not re.search(r'(^$)|(^[A-Fa-f0-9]{24}$)', subscription_id)):  # noqa: E501
            raise ValueError(r"Invalid value for `subscription_id`, must be a follow pattern or equal to `/(^$)|(^[A-Fa-f0-9]{24}$)/`")  # noqa: E501

        self._subscription_id = subscription_id

    @property
    def type(self):
        """Gets the type of this RunExportReportTaskVM.  # noqa: E501


        :return: The type of this RunExportReportTaskVM.  # noqa: E501
        :rtype: TaskType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RunExportReportTaskVM.


        :param type: The type of this RunExportReportTaskVM.  # noqa: E501
        :type type: TaskType
        """

        self._type = type

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunExportReportTaskVM):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RunExportReportTaskVM):
            return True

        return self.to_dict() != other.to_dict()
