# coding: utf-8

"""
    FastReport Cloud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from fastreport_cloud_sdk.configuration import Configuration


class UserProfileVM(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'username': 'str',
        'email': 'str',
        'is_read_only': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'username': 'username',
        'email': 'email',
        'is_read_only': 'isReadOnly'
    }

    def __init__(self, id=None, name=None, username=None, email=None, is_read_only=None, local_vars_configuration=None):  # noqa: E501
        """UserProfileVM - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._username = None
        self._email = None
        self._is_read_only = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if username is not None:
            self.username = username
        if email is not None:
            self.email = email
        if is_read_only is not None:
            self.is_read_only = is_read_only

    @property
    def id(self):
        """Gets the id of this UserProfileVM.  # noqa: E501


        :return: The id of this UserProfileVM.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserProfileVM.


        :param id: The id of this UserProfileVM.  # noqa: E501
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this UserProfileVM.  # noqa: E501


        :return: The name of this UserProfileVM.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserProfileVM.


        :param name: The name of this UserProfileVM.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def username(self):
        """Gets the username of this UserProfileVM.  # noqa: E501


        :return: The username of this UserProfileVM.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserProfileVM.


        :param username: The username of this UserProfileVM.  # noqa: E501
        :type username: str
        """

        self._username = username

    @property
    def email(self):
        """Gets the email of this UserProfileVM.  # noqa: E501


        :return: The email of this UserProfileVM.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserProfileVM.


        :param email: The email of this UserProfileVM.  # noqa: E501
        :type email: str
        """

        self._email = email

    @property
    def is_read_only(self):
        """Gets the is_read_only of this UserProfileVM.  # noqa: E501


        :return: The is_read_only of this UserProfileVM.  # noqa: E501
        :rtype: bool
        """
        return self._is_read_only

    @is_read_only.setter
    def is_read_only(self, is_read_only):
        """Sets the is_read_only of this UserProfileVM.


        :param is_read_only: The is_read_only of this UserProfileVM.  # noqa: E501
        :type is_read_only: bool
        """

        self._is_read_only = is_read_only

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserProfileVM):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserProfileVM):
            return True

        return self.to_dict() != other.to_dict()
